name: Generate Executable

on:
  # push:
  #   branches: [ main ]
  release:
    types: [released]
  workflow_dispatch:

jobs:
  generate_win_exe:
    name: Generate windows executable
    runs-on: windows-latest
    steps:
    - name: Pyinstaller build
      uses: sayyid5416/pyinstaller@v1
      with:
        spec: src/build.spec
        requirements: src/requirements.txt
        upload_exe_with_name: 'Links-Extractor'
